resources
| where type =~ 'microsoft.web/serverfarms'
| extend os = iff(kind == 'linux', 'linux', iff(kind == 'app', 'windows', kind))
| project subscriptionId, resourceGroup, name, location, os, skuName = sku.name, zoneRedundant = iff(properties.zoneRedundant == true, 'Enabled', 'Not Enabled'), instanceCount = properties.numberOfWorkers, id
| join kind=leftouter (resourcecontainers | where type == 'microsoft.resources/subscriptions' | project subscriptionId, subscriptionName = name) on subscriptionId
| project subscriptionId, subscriptionName, resourceGroup, resourceName = name, location, skuName, zoneRedundant, os, instanceCount, resourceId = id
| order by  resourceGroup asc , resourceName asc 
